// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CourseLevel.
const (
	CourseLevelAdvanced     CourseLevel = "advanced"
	CourseLevelBeginner     CourseLevel = "beginner"
	CourseLevelIntermediate CourseLevel = "intermediate"
)

// Defines values for CourseStatus.
const (
	CourseStatusArchived  CourseStatus = "archived"
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
)

// Defines values for CourseCreateLevel.
const (
	CourseCreateLevelAdvanced     CourseCreateLevel = "advanced"
	CourseCreateLevelBeginner     CourseCreateLevel = "beginner"
	CourseCreateLevelIntermediate CourseCreateLevel = "intermediate"
)

// Defines values for CourseUpdateLevel.
const (
	Advanced     CourseUpdateLevel = "advanced"
	Beginner     CourseUpdateLevel = "beginner"
	Intermediate CourseUpdateLevel = "intermediate"
)

// Defines values for CourseUpdateStatus.
const (
	CourseUpdateStatusArchived  CourseUpdateStatus = "archived"
	CourseUpdateStatusDraft     CourseUpdateStatus = "draft"
	CourseUpdateStatusPublished CourseUpdateStatus = "published"
)

// Defines values for EnrollmentStatus.
const (
	Active    EnrollmentStatus = "active"
	Completed EnrollmentStatus = "completed"
	Expired   EnrollmentStatus = "expired"
	Refunded  EnrollmentStatus = "refunded"
)

// Defines values for LessonType.
const (
	LessonTypeAssignment LessonType = "assignment"
	LessonTypeCoding     LessonType = "coding"
	LessonTypeEmbed      LessonType = "embed"
	LessonTypePdf        LessonType = "pdf"
	LessonTypeQuiz       LessonType = "quiz"
	LessonTypeText       LessonType = "text"
	LessonTypeVideo      LessonType = "video"
)

// Defines values for LessonCreateType.
const (
	LessonCreateTypeAssignment LessonCreateType = "assignment"
	LessonCreateTypeCoding     LessonCreateType = "coding"
	LessonCreateTypeEmbed      LessonCreateType = "embed"
	LessonCreateTypePdf        LessonCreateType = "pdf"
	LessonCreateTypeQuiz       LessonCreateType = "quiz"
	LessonCreateTypeText       LessonCreateType = "text"
	LessonCreateTypeVideo      LessonCreateType = "video"
)

// Defines values for LessonUpdateType.
const (
	Assignment LessonUpdateType = "assignment"
	Coding     LessonUpdateType = "coding"
	Embed      LessonUpdateType = "embed"
	Pdf        LessonUpdateType = "pdf"
	Quiz       LessonUpdateType = "quiz"
	Text       LessonUpdateType = "text"
	Video      LessonUpdateType = "video"
)

// Defines values for UserRole.
const (
	Admin      UserRole = "admin"
	Instructor UserRole = "instructor"
	Student    UserRole = "student"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Data      *map[string]interface{} `json:"data"`
	RequestID *string                 `json:"requestID,omitempty"`
	Status    *int                    `json:"status,omitempty"`
	Success   *bool                   `json:"success,omitempty"`
}

// Course defines model for Course.
type Course struct {
	CoverUrl    *string       `json:"coverUrl,omitempty"`
	CreatedAt   *time.Time    `json:"createdAt,omitempty"`
	Currency    *string       `json:"currency,omitempty"`
	Description *string       `json:"description,omitempty"`
	Id          *int64        `json:"id,omitempty"`
	Level       *CourseLevel  `json:"level,omitempty"`
	Price       *float32      `json:"price,omitempty"`
	Slug        *string       `json:"slug,omitempty"`
	Status      *CourseStatus `json:"status,omitempty"`
	Subtitle    *string       `json:"subtitle,omitempty"`
	Title       *string       `json:"title,omitempty"`
	UpdatedAt   *time.Time    `json:"updatedAt,omitempty"`
}

// CourseLevel defines model for Course.Level.
type CourseLevel string

// CourseStatus defines model for Course.Status.
type CourseStatus string

// CourseCreate defines model for CourseCreate.
type CourseCreate struct {
	CoverUrl    *string            `json:"coverUrl,omitempty"`
	Currency    *string            `json:"currency,omitempty"`
	Description *string            `json:"description,omitempty"`
	Level       *CourseCreateLevel `json:"level,omitempty"`
	Price       *float32           `json:"price,omitempty"`
	Slug        string             `json:"slug"`
	Subtitle    *string            `json:"subtitle,omitempty"`
	Title       string             `json:"title"`
}

// CourseCreateLevel defines model for CourseCreate.Level.
type CourseCreateLevel string

// CourseUpdate defines model for CourseUpdate.
type CourseUpdate struct {
	CoverUrl    *string             `json:"coverUrl,omitempty"`
	Currency    *string             `json:"currency,omitempty"`
	Description *string             `json:"description,omitempty"`
	Level       *CourseUpdateLevel  `json:"level,omitempty"`
	Price       *float32            `json:"price,omitempty"`
	Slug        *string             `json:"slug,omitempty"`
	Status      *CourseUpdateStatus `json:"status,omitempty"`
	Subtitle    *string             `json:"subtitle,omitempty"`
	Title       *string             `json:"title,omitempty"`
}

// CourseUpdateLevel defines model for CourseUpdate.Level.
type CourseUpdateLevel string

// CourseUpdateStatus defines model for CourseUpdate.Status.
type CourseUpdateStatus string

// Enrollment defines model for Enrollment.
type Enrollment struct {
	CompletedAt *time.Time `json:"completedAt"`
	EnrolledAt  *time.Time `json:"enrolledAt,omitempty"`
	Id          *int64     `json:"id,omitempty"`

	// Progress 0-100
	Progress *float32          `json:"progress,omitempty"`
	Status   *EnrollmentStatus `json:"status,omitempty"`
}

// EnrollmentStatus defines model for Enrollment.Status.
type EnrollmentStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

// Lesson defines model for Lesson.
type Lesson struct {
	// Content URL видео, текст, markdown, JSON для quiz и т.д.
	Content     *string    `json:"content,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	DurationSec *int       `json:"durationSec"`
	Id          *int64     `json:"id,omitempty"`
	IsPublished *bool      `json:"isPublished,omitempty"`

	// Order Порядковый номер урока внутри раздела
	Order     *int        `json:"order,omitempty"`
	SectionId *int64      `json:"sectionId,omitempty"`
	Title     *string     `json:"title,omitempty"`
	Type      *LessonType `json:"type,omitempty"`
	UpdatedAt *time.Time  `json:"updatedAt,omitempty"`
}

// LessonType defines model for Lesson.Type.
type LessonType string

// LessonCreate defines model for LessonCreate.
type LessonCreate struct {
	Content     *string          `json:"content,omitempty"`
	DurationSec *int             `json:"durationSec,omitempty"`
	IsPublished *bool            `json:"isPublished,omitempty"`
	Order       int              `json:"order"`
	Title       string           `json:"title"`
	Type        LessonCreateType `json:"type"`
}

// LessonCreateType defines model for LessonCreate.Type.
type LessonCreateType string

// LessonUpdate defines model for LessonUpdate.
type LessonUpdate struct {
	Content     *string           `json:"content,omitempty"`
	DurationSec *int              `json:"durationSec,omitempty"`
	IsPublished *bool             `json:"isPublished,omitempty"`
	Order       *int              `json:"order,omitempty"`
	Title       *string           `json:"title,omitempty"`
	Type        *LessonUpdateType `json:"type,omitempty"`
}

// LessonUpdateType defines model for LessonUpdate.Type.
type LessonUpdateType string

// Section defines model for Section.
type Section struct {
	CourseId  *int64     `json:"courseId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// EstimatedTime minutes
	EstimatedTime *int       `json:"estimatedTime,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	IsFreePreview *bool      `json:"isFreePreview,omitempty"`
	Order         *int       `json:"order,omitempty"`
	Title         *string    `json:"title,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
}

// SectionCreate defines model for SectionCreate.
type SectionCreate struct {
	// EstimatedTime minutes
	EstimatedTime *int   `json:"estimatedTime,omitempty"`
	IsFreePreview *bool  `json:"isFreePreview,omitempty"`
	Order         int    `json:"order"`
	Title         string `json:"title"`
}

// SectionUpdate defines model for SectionUpdate.
type SectionUpdate struct {
	EstimatedTime *int    `json:"estimatedTime,omitempty"`
	IsFreePreview *bool   `json:"isFreePreview,omitempty"`
	Order         *int    `json:"order,omitempty"`
	Title         *string `json:"title,omitempty"`
}

// TokenRefreshRequest defines model for TokenRefreshRequest.
type TokenRefreshRequest struct {
	// RefreshToken Refresh токен, полученный при логине
	RefreshToken string `json:"refreshToken"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Новый access-токен (JWT)
	AccessToken string `json:"accessToken"`

	// ExpiresIn Время жизни access-токена в секундах (например 900 = 15 мин)
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// RefreshToken Новый refresh-токен (opaque token, rotation)
	RefreshToken string `json:"refreshToken"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string              `json:"avatarUrl"`
	CreatedAt *time.Time           `json:"createdAt,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	FullName  *string              `json:"fullName,omitempty"`
	Id        *int64               `json:"id,omitempty"`
	Role      *UserRole            `json:"role,omitempty"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Password string              `json:"password"`
}

// UserDeleteRequest defines model for UserDeleteRequest.
type UserDeleteRequest struct {
	// Password Текущий пароль для подтверждения удаления
	Password string `json:"password"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	AvatarUrl *string `json:"avatarUrl"`

	// CurrentPassword Текущий пароль (обязателен при смене пароля)
	CurrentPassword *string `json:"currentPassword,omitempty"`
	FullName        *string `json:"fullName,omitempty"`

	// Password Новый пароль (если меняется)
	Password *string `json:"password,omitempty"`
}

// AuthLoginUserJSONBody defines parameters for AuthLoginUser.
type AuthLoginUserJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetCoursesParams defines parameters for GetCourses.
type GetCoursesParams struct {
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Category *string `form:"category,omitempty" json:"category,omitempty"`
	Level    *string `form:"level,omitempty" json:"level,omitempty"`

	// Search Поиск по названию или описанию
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetLessonsParams defines parameters for GetLessons.
type GetLessonsParams struct {
	// PublishedOnly Показывать только опубликованные уроки (для студентов)
	PublishedOnly *bool `form:"publishedOnly,omitempty" json:"publishedOnly,omitempty"`
}

// EnrollCourseJSONBody defines parameters for EnrollCourse.
type EnrollCourseJSONBody struct {
	PromoCode *string `json:"promoCode,omitempty"`
}

// UpdateLessonProgressJSONBody defines parameters for UpdateLessonProgress.
type UpdateLessonProgressJSONBody struct {
	Completed      *bool    `json:"completed,omitempty"`
	LastWatchedSec *int     `json:"lastWatchedSec,omitempty"`
	Percent        *float32 `json:"percent,omitempty"`
}

// AuthLoginUserJSONRequestBody defines body for AuthLoginUser for application/json ContentType.
type AuthLoginUserJSONRequestBody AuthLoginUserJSONBody

// AuthRefreshTokenJSONRequestBody defines body for AuthRefreshToken for application/json ContentType.
type AuthRefreshTokenJSONRequestBody = TokenRefreshRequest

// AuthRegisterUserJSONRequestBody defines body for AuthRegisterUser for application/json ContentType.
type AuthRegisterUserJSONRequestBody = UserCreate

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseCreate

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseUpdate

// CreateSectionJSONRequestBody defines body for CreateSection for application/json ContentType.
type CreateSectionJSONRequestBody = SectionCreate

// UpdateSectionJSONRequestBody defines body for UpdateSection for application/json ContentType.
type UpdateSectionJSONRequestBody = SectionUpdate

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonCreate

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonUpdate

// EnrollCourseJSONRequestBody defines body for EnrollCourse for application/json ContentType.
type EnrollCourseJSONRequestBody EnrollCourseJSONBody

// DeleteCurrentUserJSONRequestBody defines body for DeleteCurrentUser for application/json ContentType.
type DeleteCurrentUserJSONRequestBody = UserDeleteRequest

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UserUpdate

// UpdateLessonProgressJSONRequestBody defines body for UpdateLessonProgress for application/json ContentType.
type UpdateLessonProgressJSONRequestBody UpdateLessonProgressJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Авторизация пользователя
	// (POST /auth/login)
	AuthLoginUser(w http.ResponseWriter, r *http.Request)
	// Обновление access-токена с помощью refresh-токена (token rotation)
	// (POST /auth/refresh)
	AuthRefreshToken(w http.ResponseWriter, r *http.Request)
	// Регистрация нового пользователя
	// (POST /auth/register)
	AuthRegisterUser(w http.ResponseWriter, r *http.Request)
	// Список всех опубликованных курсов (для всех пользователей)
	// (GET /courses)
	GetCourses(w http.ResponseWriter, r *http.Request, params GetCoursesParams)
	// Создание нового курса (только для преподавателей и админов)
	// (POST /courses)
	CreateCourse(w http.ResponseWriter, r *http.Request)
	// Удалить курс (только для админов или владельца)
	// (DELETE /courses/{courseID})
	DeleteCourse(w http.ResponseWriter, r *http.Request, courseID string)
	// Получить подробную информацию о курсе
	// (GET /courses/{courseID})
	GetCourseByID(w http.ResponseWriter, r *http.Request, courseID string)
	// Частично обновить курс (для преподавателей и админов)
	// (PATCH /courses/{courseID})
	UpdateCourse(w http.ResponseWriter, r *http.Request, courseID string)
	// Получить все разделы курса
	// (GET /courses/{courseID}/sections)
	GetSections(w http.ResponseWriter, r *http.Request, courseID string)
	// Создать новый раздел в курсе (для преподавателей/админов)
	// (POST /courses/{courseID}/sections)
	CreateSection(w http.ResponseWriter, r *http.Request, courseID string)
	// Удалить раздел (для преподавателей/админов)
	// (DELETE /courses/{courseID}/sections/{sectionID})
	DeleteSection(w http.ResponseWriter, r *http.Request, courseID string, sectionID string)
	// Получить информацию об одном разделе курса
	// (GET /courses/{courseID}/sections/{sectionID})
	GetSectionByID(w http.ResponseWriter, r *http.Request, courseID string, sectionID string)
	// Обновить раздел (для преподавателей/админов)
	// (PATCH /courses/{courseID}/sections/{sectionID})
	UpdateSection(w http.ResponseWriter, r *http.Request, courseID string, sectionID string)
	// Получить список всех уроков в разделе курса
	// (GET /courses/{courseID}/sections/{sectionID}/lessons)
	GetLessons(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, params GetLessonsParams)
	// Создать новый урок в разделе (для преподавателей/админов)
	// (POST /courses/{courseID}/sections/{sectionID}/lessons)
	CreateLesson(w http.ResponseWriter, r *http.Request, courseID string, sectionID string)
	// Удалить урок (для преподавателей/админов)
	// (DELETE /courses/{courseID}/sections/{sectionID}/lessons/{lessonID})
	DeleteLesson(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, lessonID string)
	// Получить информацию об одном уроке
	// (GET /courses/{courseID}/sections/{sectionID}/lessons/{lessonID})
	GetLessonByID(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, lessonID string)
	// Обновить урок (для преподавателей/админов)
	// (PATCH /courses/{courseID}/sections/{sectionID}/lessons/{lessonID})
	UpdateLesson(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, lessonID string)
	// Записаться на курс / купить курс
	// (POST /courses/{courseId}/enroll)
	EnrollCourse(w http.ResponseWriter, r *http.Request, courseId int)
	// Удалить аккаунт текущего пользователя (с подтверждением паролем)
	// (DELETE /me)
	DeleteCurrentUser(w http.ResponseWriter, r *http.Request)
	// Получить информацию о текущем пользователе
	// (GET /me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Обновить данные текущего пользователя (fullName, avatar, пароль)
	// (PATCH /me)
	UpdateCurrentUser(w http.ResponseWriter, r *http.Request)
	// Обновить прогресс урока
	// (PATCH /me/courses/{courseID}/lessons/{lessonID}/progress)
	UpdateLessonProgress(w http.ResponseWriter, r *http.Request, courseID string, lessonID string)
	// Прогресс пользователя по всем курсам
	// (GET /me/progress)
	GetUserProgress(w http.ResponseWriter, r *http.Request)
	// Удалить пользователя (только для админов)
	// (DELETE /users/{userId})
	DeleteUserById(w http.ResponseWriter, r *http.Request, userId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Авторизация пользователя
// (POST /auth/login)
func (_ Unimplemented) AuthLoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновление access-токена с помощью refresh-токена (token rotation)
// (POST /auth/refresh)
func (_ Unimplemented) AuthRefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация нового пользователя
// (POST /auth/register)
func (_ Unimplemented) AuthRegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список всех опубликованных курсов (для всех пользователей)
// (GET /courses)
func (_ Unimplemented) GetCourses(w http.ResponseWriter, r *http.Request, params GetCoursesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создание нового курса (только для преподавателей и админов)
// (POST /courses)
func (_ Unimplemented) CreateCourse(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить курс (только для админов или владельца)
// (DELETE /courses/{courseID})
func (_ Unimplemented) DeleteCourse(w http.ResponseWriter, r *http.Request, courseID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить подробную информацию о курсе
// (GET /courses/{courseID})
func (_ Unimplemented) GetCourseByID(w http.ResponseWriter, r *http.Request, courseID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Частично обновить курс (для преподавателей и админов)
// (PATCH /courses/{courseID})
func (_ Unimplemented) UpdateCourse(w http.ResponseWriter, r *http.Request, courseID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить все разделы курса
// (GET /courses/{courseID}/sections)
func (_ Unimplemented) GetSections(w http.ResponseWriter, r *http.Request, courseID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новый раздел в курсе (для преподавателей/админов)
// (POST /courses/{courseID}/sections)
func (_ Unimplemented) CreateSection(w http.ResponseWriter, r *http.Request, courseID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить раздел (для преподавателей/админов)
// (DELETE /courses/{courseID}/sections/{sectionID})
func (_ Unimplemented) DeleteSection(w http.ResponseWriter, r *http.Request, courseID string, sectionID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию об одном разделе курса
// (GET /courses/{courseID}/sections/{sectionID})
func (_ Unimplemented) GetSectionByID(w http.ResponseWriter, r *http.Request, courseID string, sectionID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить раздел (для преподавателей/админов)
// (PATCH /courses/{courseID}/sections/{sectionID})
func (_ Unimplemented) UpdateSection(w http.ResponseWriter, r *http.Request, courseID string, sectionID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список всех уроков в разделе курса
// (GET /courses/{courseID}/sections/{sectionID}/lessons)
func (_ Unimplemented) GetLessons(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, params GetLessonsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новый урок в разделе (для преподавателей/админов)
// (POST /courses/{courseID}/sections/{sectionID}/lessons)
func (_ Unimplemented) CreateLesson(w http.ResponseWriter, r *http.Request, courseID string, sectionID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить урок (для преподавателей/админов)
// (DELETE /courses/{courseID}/sections/{sectionID}/lessons/{lessonID})
func (_ Unimplemented) DeleteLesson(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, lessonID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию об одном уроке
// (GET /courses/{courseID}/sections/{sectionID}/lessons/{lessonID})
func (_ Unimplemented) GetLessonByID(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, lessonID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить урок (для преподавателей/админов)
// (PATCH /courses/{courseID}/sections/{sectionID}/lessons/{lessonID})
func (_ Unimplemented) UpdateLesson(w http.ResponseWriter, r *http.Request, courseID string, sectionID string, lessonID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Записаться на курс / купить курс
// (POST /courses/{courseId}/enroll)
func (_ Unimplemented) EnrollCourse(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить аккаунт текущего пользователя (с подтверждением паролем)
// (DELETE /me)
func (_ Unimplemented) DeleteCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о текущем пользователе
// (GET /me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить данные текущего пользователя (fullName, avatar, пароль)
// (PATCH /me)
func (_ Unimplemented) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить прогресс урока
// (PATCH /me/courses/{courseID}/lessons/{lessonID}/progress)
func (_ Unimplemented) UpdateLessonProgress(w http.ResponseWriter, r *http.Request, courseID string, lessonID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Прогресс пользователя по всем курсам
// (GET /me/progress)
func (_ Unimplemented) GetUserProgress(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить пользователя (только для админов)
// (DELETE /users/{userId})
func (_ Unimplemented) DeleteUserById(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthLoginUser operation middleware
func (siw *ServerInterfaceWrapper) AuthLoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRefreshToken operation middleware
func (siw *ServerInterfaceWrapper) AuthRefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRegisterUser operation middleware
func (siw *ServerInterfaceWrapper) AuthRegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCourses operation middleware
func (siw *ServerInterfaceWrapper) GetCourses(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCoursesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", r.URL.Query(), &params.Category)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		return
	}

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameter("form", true, false, "level", r.URL.Query(), &params.Level)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCourses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCourse operation middleware
func (siw *ServerInterfaceWrapper) CreateCourse(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCourse(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCourse operation middleware
func (siw *ServerInterfaceWrapper) DeleteCourse(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCourse(w, r, courseID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCourseByID operation middleware
func (siw *ServerInterfaceWrapper) GetCourseByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCourseByID(w, r, courseID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCourse operation middleware
func (siw *ServerInterfaceWrapper) UpdateCourse(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCourse(w, r, courseID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSections operation middleware
func (siw *ServerInterfaceWrapper) GetSections(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSections(w, r, courseID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSection operation middleware
func (siw *ServerInterfaceWrapper) CreateSection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSection(w, r, courseID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSection operation middleware
func (siw *ServerInterfaceWrapper) DeleteSection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSection(w, r, courseID, sectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSectionByID operation middleware
func (siw *ServerInterfaceWrapper) GetSectionByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSectionByID(w, r, courseID, sectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSection operation middleware
func (siw *ServerInterfaceWrapper) UpdateSection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSection(w, r, courseID, sectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLessons operation middleware
func (siw *ServerInterfaceWrapper) GetLessons(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLessonsParams

	// ------------- Optional query parameter "publishedOnly" -------------

	err = runtime.BindQueryParameter("form", true, false, "publishedOnly", r.URL.Query(), &params.PublishedOnly)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publishedOnly", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLessons(w, r, courseID, sectionID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLesson operation middleware
func (siw *ServerInterfaceWrapper) CreateLesson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLesson(w, r, courseID, sectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLesson operation middleware
func (siw *ServerInterfaceWrapper) DeleteLesson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	// ------------- Path parameter "lessonID" -------------
	var lessonID string

	err = runtime.BindStyledParameterWithOptions("simple", "lessonID", chi.URLParam(r, "lessonID"), &lessonID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLesson(w, r, courseID, sectionID, lessonID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLessonByID operation middleware
func (siw *ServerInterfaceWrapper) GetLessonByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	// ------------- Path parameter "lessonID" -------------
	var lessonID string

	err = runtime.BindStyledParameterWithOptions("simple", "lessonID", chi.URLParam(r, "lessonID"), &lessonID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLessonByID(w, r, courseID, sectionID, lessonID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLesson operation middleware
func (siw *ServerInterfaceWrapper) UpdateLesson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "sectionID" -------------
	var sectionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sectionID", chi.URLParam(r, "sectionID"), &sectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionID", Err: err})
		return
	}

	// ------------- Path parameter "lessonID" -------------
	var lessonID string

	err = runtime.BindStyledParameterWithOptions("simple", "lessonID", chi.URLParam(r, "lessonID"), &lessonID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLesson(w, r, courseID, sectionID, lessonID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollCourse operation middleware
func (siw *ServerInterfaceWrapper) EnrollCourse(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollCourse(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLessonProgress operation middleware
func (siw *ServerInterfaceWrapper) UpdateLessonProgress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseID" -------------
	var courseID string

	err = runtime.BindStyledParameterWithOptions("simple", "courseID", chi.URLParam(r, "courseID"), &courseID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseID", Err: err})
		return
	}

	// ------------- Path parameter "lessonID" -------------
	var lessonID string

	err = runtime.BindStyledParameterWithOptions("simple", "lessonID", chi.URLParam(r, "lessonID"), &lessonID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLessonProgress(w, r, courseID, lessonID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserProgress operation middleware
func (siw *ServerInterfaceWrapper) GetUserProgress(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserProgress(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserById operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserById(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.AuthLoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.AuthRefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.AuthRegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses", wrapper.GetCourses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses", wrapper.CreateCourse)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/courses/{courseID}", wrapper.DeleteCourse)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseID}", wrapper.GetCourseByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/courses/{courseID}", wrapper.UpdateCourse)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseID}/sections", wrapper.GetSections)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseID}/sections", wrapper.CreateSection)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/courses/{courseID}/sections/{sectionID}", wrapper.DeleteSection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseID}/sections/{sectionID}", wrapper.GetSectionByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/courses/{courseID}/sections/{sectionID}", wrapper.UpdateSection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseID}/sections/{sectionID}/lessons", wrapper.GetLessons)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseID}/sections/{sectionID}/lessons", wrapper.CreateLesson)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/courses/{courseID}/sections/{sectionID}/lessons/{lessonID}", wrapper.DeleteLesson)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseID}/sections/{sectionID}/lessons/{lessonID}", wrapper.GetLessonByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/courses/{courseID}/sections/{sectionID}/lessons/{lessonID}", wrapper.UpdateLesson)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseId}/enroll", wrapper.EnrollCourse)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me", wrapper.DeleteCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me/courses/{courseID}/lessons/{lessonID}/progress", wrapper.UpdateLessonProgress)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/progress", wrapper.GetUserProgress)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{userId}", wrapper.DeleteUserById)
	})

	return r
}
