// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CourseLevel.
const (
	CourseLevelAdvanced     CourseLevel = "advanced"
	CourseLevelBeginner     CourseLevel = "beginner"
	CourseLevelIntermediate CourseLevel = "intermediate"
)

// Defines values for CourseStatus.
const (
	CourseStatusArchived  CourseStatus = "archived"
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
)

// Defines values for CourseCreateLevel.
const (
	CourseCreateLevelAdvanced     CourseCreateLevel = "advanced"
	CourseCreateLevelBeginner     CourseCreateLevel = "beginner"
	CourseCreateLevelIntermediate CourseCreateLevel = "intermediate"
)

// Defines values for CourseUpdateLevel.
const (
	Advanced     CourseUpdateLevel = "advanced"
	Beginner     CourseUpdateLevel = "beginner"
	Intermediate CourseUpdateLevel = "intermediate"
)

// Defines values for CourseUpdateStatus.
const (
	CourseUpdateStatusArchived  CourseUpdateStatus = "archived"
	CourseUpdateStatusDraft     CourseUpdateStatus = "draft"
	CourseUpdateStatusPublished CourseUpdateStatus = "published"
)

// Defines values for EnrollmentStatus.
const (
	Active    EnrollmentStatus = "active"
	Completed EnrollmentStatus = "completed"
	Expired   EnrollmentStatus = "expired"
	Refunded  EnrollmentStatus = "refunded"
)

// Defines values for LessonType.
const (
	LessonTypeAssignment LessonType = "assignment"
	LessonTypeCoding     LessonType = "coding"
	LessonTypeEmbed      LessonType = "embed"
	LessonTypePdf        LessonType = "pdf"
	LessonTypeQuiz       LessonType = "quiz"
	LessonTypeText       LessonType = "text"
	LessonTypeVideo      LessonType = "video"
)

// Defines values for LessonCreateType.
const (
	LessonCreateTypeAssignment LessonCreateType = "assignment"
	LessonCreateTypeCoding     LessonCreateType = "coding"
	LessonCreateTypeEmbed      LessonCreateType = "embed"
	LessonCreateTypePdf        LessonCreateType = "pdf"
	LessonCreateTypeQuiz       LessonCreateType = "quiz"
	LessonCreateTypeText       LessonCreateType = "text"
	LessonCreateTypeVideo      LessonCreateType = "video"
)

// Defines values for LessonUpdateType.
const (
	Assignment LessonUpdateType = "assignment"
	Coding     LessonUpdateType = "coding"
	Embed      LessonUpdateType = "embed"
	Pdf        LessonUpdateType = "pdf"
	Quiz       LessonUpdateType = "quiz"
	Text       LessonUpdateType = "text"
	Video      LessonUpdateType = "video"
)

// Defines values for UserRole.
const (
	Admin      UserRole = "admin"
	Instructor UserRole = "instructor"
	Student    UserRole = "student"
)

// Course defines model for Course.
type Course struct {
	CoverUrl    *string       `json:"coverUrl,omitempty"`
	CreatedAt   *time.Time    `json:"createdAt,omitempty"`
	Currency    *string       `json:"currency,omitempty"`
	Description *string       `json:"description,omitempty"`
	Id          *int64        `json:"id,omitempty"`
	Level       *CourseLevel  `json:"level,omitempty"`
	Price       *float32      `json:"price,omitempty"`
	Slug        *string       `json:"slug,omitempty"`
	Status      *CourseStatus `json:"status,omitempty"`
	Subtitle    *string       `json:"subtitle,omitempty"`
	Title       *string       `json:"title,omitempty"`
	UpdatedAt   *time.Time    `json:"updatedAt,omitempty"`
}

// CourseLevel defines model for Course.Level.
type CourseLevel string

// CourseStatus defines model for Course.Status.
type CourseStatus string

// CourseCreate defines model for CourseCreate.
type CourseCreate struct {
	CoverUrl    *string            `json:"coverUrl,omitempty"`
	Currency    *string            `json:"currency,omitempty"`
	Description *string            `json:"description,omitempty"`
	Level       *CourseCreateLevel `json:"level,omitempty"`
	Price       *float32           `json:"price,omitempty"`
	Slug        string             `json:"slug"`
	Subtitle    *string            `json:"subtitle,omitempty"`
	Title       string             `json:"title"`
}

// CourseCreateLevel defines model for CourseCreate.Level.
type CourseCreateLevel string

// CourseUpdate defines model for CourseUpdate.
type CourseUpdate struct {
	CoverUrl    *string             `json:"coverUrl,omitempty"`
	Currency    *string             `json:"currency,omitempty"`
	Description *string             `json:"description,omitempty"`
	Level       *CourseUpdateLevel  `json:"level,omitempty"`
	Price       *float32            `json:"price,omitempty"`
	Slug        *string             `json:"slug,omitempty"`
	Status      *CourseUpdateStatus `json:"status,omitempty"`
	Subtitle    *string             `json:"subtitle,omitempty"`
	Title       *string             `json:"title,omitempty"`
}

// CourseUpdateLevel defines model for CourseUpdate.Level.
type CourseUpdateLevel string

// CourseUpdateStatus defines model for CourseUpdate.Status.
type CourseUpdateStatus string

// Enrollment defines model for Enrollment.
type Enrollment struct {
	CompletedAt *time.Time `json:"completedAt"`
	EnrolledAt  *time.Time `json:"enrolledAt,omitempty"`
	Id          *int64     `json:"id,omitempty"`

	// Progress 0-100
	Progress *float32          `json:"progress,omitempty"`
	Status   *EnrollmentStatus `json:"status,omitempty"`
}

// EnrollmentStatus defines model for Enrollment.Status.
type EnrollmentStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

// Lesson defines model for Lesson.
type Lesson struct {
	// Content URL видео, текст, markdown, JSON для quiz и т.д.
	Content     *string    `json:"content,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	DurationSec *int       `json:"durationSec"`
	Id          *int64     `json:"id,omitempty"`
	IsPublished *bool      `json:"isPublished,omitempty"`

	// Order Порядковый номер урока внутри раздела
	Order     *int        `json:"order,omitempty"`
	SectionId *int64      `json:"sectionId,omitempty"`
	Title     *string     `json:"title,omitempty"`
	Type      *LessonType `json:"type,omitempty"`
	UpdatedAt *time.Time  `json:"updatedAt,omitempty"`
}

// LessonType defines model for Lesson.Type.
type LessonType string

// LessonCreate defines model for LessonCreate.
type LessonCreate struct {
	Content     *string          `json:"content,omitempty"`
	DurationSec *int             `json:"durationSec,omitempty"`
	IsPublished *bool            `json:"isPublished,omitempty"`
	Order       int              `json:"order"`
	Title       string           `json:"title"`
	Type        LessonCreateType `json:"type"`
}

// LessonCreateType defines model for LessonCreate.Type.
type LessonCreateType string

// LessonUpdate defines model for LessonUpdate.
type LessonUpdate struct {
	Content     *string           `json:"content,omitempty"`
	DurationSec *int              `json:"durationSec,omitempty"`
	IsPublished *bool             `json:"isPublished,omitempty"`
	Order       *int              `json:"order,omitempty"`
	Title       *string           `json:"title,omitempty"`
	Type        *LessonUpdateType `json:"type,omitempty"`
}

// LessonUpdateType defines model for LessonUpdate.Type.
type LessonUpdateType string

// Section defines model for Section.
type Section struct {
	CourseId  *int64     `json:"courseId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// EstimatedTime minutes
	EstimatedTime *int       `json:"estimatedTime,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	IsFreePreview *bool      `json:"isFreePreview,omitempty"`
	Order         *int       `json:"order,omitempty"`
	Title         *string    `json:"title,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
}

// SectionCreate defines model for SectionCreate.
type SectionCreate struct {
	// EstimatedTime minutes
	EstimatedTime *int   `json:"estimatedTime,omitempty"`
	IsFreePreview *bool  `json:"isFreePreview,omitempty"`
	Order         int    `json:"order"`
	Title         string `json:"title"`
}

// SectionUpdate defines model for SectionUpdate.
type SectionUpdate struct {
	EstimatedTime *int    `json:"estimatedTime,omitempty"`
	IsFreePreview *bool   `json:"isFreePreview,omitempty"`
	Order         *int    `json:"order,omitempty"`
	Title         *string `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string              `json:"avatarUrl"`
	CreatedAt *time.Time           `json:"createdAt,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	FullName  *string              `json:"fullName,omitempty"`
	Id        *int64               `json:"id,omitempty"`
	Role      *UserRole            `json:"role,omitempty"`
}

// UserRole defines model for User.Role.
type UserRole string

// AuthLoginUserJSONBody defines parameters for AuthLoginUser.
type AuthLoginUserJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// AuthRegisterUserJSONBody defines parameters for AuthRegisterUser.
type AuthRegisterUserJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Password string              `json:"password"`
}

// CoursesListParams defines parameters for CoursesList.
type CoursesListParams struct {
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Category *string `form:"category,omitempty" json:"category,omitempty"`
	Level    *string `form:"level,omitempty" json:"level,omitempty"`

	// Search Поиск по названию или описанию
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// EnrollmentsEnrollInCourseJSONBody defines parameters for EnrollmentsEnrollInCourse.
type EnrollmentsEnrollInCourseJSONBody struct {
	PromoCode *string `json:"promoCode,omitempty"`
}

// CoursesGetSectionsParams defines parameters for CoursesGetSections.
type CoursesGetSectionsParams struct {
	// IncludeUnpublished Включать неопубликованные разделы (для авторов курса)
	IncludeUnpublished *bool `form:"includeUnpublished,omitempty" json:"includeUnpublished,omitempty"`
}

// SectionsGetLessonsParams defines parameters for SectionsGetLessons.
type SectionsGetLessonsParams struct {
	// PublishedOnly Показывать только опубликованные уроки (для студентов)
	PublishedOnly *bool `form:"publishedOnly,omitempty" json:"publishedOnly,omitempty"`
}

// ProgressUpdateLessonProgressJSONBody defines parameters for ProgressUpdateLessonProgress.
type ProgressUpdateLessonProgressJSONBody struct {
	Completed      *bool    `json:"completed,omitempty"`
	LastWatchedSec *int     `json:"lastWatchedSec,omitempty"`
	Percent        *float32 `json:"percent,omitempty"`
}

// AuthLoginUserJSONRequestBody defines body for AuthLoginUser for application/json ContentType.
type AuthLoginUserJSONRequestBody AuthLoginUserJSONBody

// AuthRegisterUserJSONRequestBody defines body for AuthRegisterUser for application/json ContentType.
type AuthRegisterUserJSONRequestBody AuthRegisterUserJSONBody

// CoursesCreateJSONRequestBody defines body for CoursesCreate for application/json ContentType.
type CoursesCreateJSONRequestBody = CourseCreate

// CoursesUpdateJSONRequestBody defines body for CoursesUpdate for application/json ContentType.
type CoursesUpdateJSONRequestBody = CourseUpdate

// EnrollmentsEnrollInCourseJSONRequestBody defines body for EnrollmentsEnrollInCourse for application/json ContentType.
type EnrollmentsEnrollInCourseJSONRequestBody EnrollmentsEnrollInCourseJSONBody

// CoursesCreateSectionJSONRequestBody defines body for CoursesCreateSection for application/json ContentType.
type CoursesCreateSectionJSONRequestBody = SectionCreate

// SectionsUpdateJSONRequestBody defines body for SectionsUpdate for application/json ContentType.
type SectionsUpdateJSONRequestBody = SectionUpdate

// SectionsCreateLessonJSONRequestBody defines body for SectionsCreateLesson for application/json ContentType.
type SectionsCreateLessonJSONRequestBody = LessonCreate

// LessonsUpdateJSONRequestBody defines body for LessonsUpdate for application/json ContentType.
type LessonsUpdateJSONRequestBody = LessonUpdate

// ProgressUpdateLessonProgressJSONRequestBody defines body for ProgressUpdateLessonProgress for application/json ContentType.
type ProgressUpdateLessonProgressJSONRequestBody ProgressUpdateLessonProgressJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Авторизация пользователя
	// (POST /auth/login)
	AuthLoginUser(w http.ResponseWriter, r *http.Request)
	// Регистрация нового пользователя
	// (POST /auth/register)
	AuthRegisterUser(w http.ResponseWriter, r *http.Request)
	// Список всех опубликованных курсов (для всех пользователей)
	// (GET /courses)
	CoursesList(w http.ResponseWriter, r *http.Request, params CoursesListParams)
	// Создание нового курса (только для преподавателей и админов)
	// (POST /courses)
	CoursesCreate(w http.ResponseWriter, r *http.Request)
	// Удалить курс (только для админов или владельца)
	// (DELETE /courses/{courseId})
	CoursesDelete(w http.ResponseWriter, r *http.Request, courseId int)
	// Получить подробную информацию о курсе
	// (GET /courses/{courseId})
	CoursesGetById(w http.ResponseWriter, r *http.Request, courseId int)
	// Частично обновить курс (для преподавателей и админов)
	// (PATCH /courses/{courseId})
	CoursesUpdate(w http.ResponseWriter, r *http.Request, courseId int)
	// Записаться на курс / купить курс
	// (POST /courses/{courseId}/enroll)
	EnrollmentsEnrollInCourse(w http.ResponseWriter, r *http.Request, courseId int)
	// Получить все разделы курса
	// (GET /courses/{courseId}/sections)
	CoursesGetSections(w http.ResponseWriter, r *http.Request, courseId int, params CoursesGetSectionsParams)
	// Создать новый раздел в курсе (для преподавателей/админов)
	// (POST /courses/{courseId}/sections)
	CoursesCreateSection(w http.ResponseWriter, r *http.Request, courseId int)
	// Удалить раздел (для преподавателей/админов)
	// (DELETE /courses/{courseId}/sections/{sectionId})
	SectionsDelete(w http.ResponseWriter, r *http.Request, courseId int, sectionId int)
	// Получить информацию об одном разделе курса
	// (GET /courses/{courseId}/sections/{sectionId})
	SectionsGetById(w http.ResponseWriter, r *http.Request, courseId int, sectionId int)
	// Обновить раздел (для преподавателей/админов)
	// (PATCH /courses/{courseId}/sections/{sectionId})
	SectionsUpdate(w http.ResponseWriter, r *http.Request, courseId int, sectionId int)
	// Получить список всех уроков в разделе курса
	// (GET /courses/{courseId}/sections/{sectionId}/lessons)
	SectionsGetLessons(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, params SectionsGetLessonsParams)
	// Создать новый урок в разделе (для преподавателей/админов)
	// (POST /courses/{courseId}/sections/{sectionId}/lessons)
	SectionsCreateLesson(w http.ResponseWriter, r *http.Request, courseId int, sectionId int)
	// Удалить урок (для преподавателей/админов)
	// (DELETE /courses/{courseId}/sections/{sectionId}/lessons/{lessonId})
	LessonsDelete(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, lessonId int)
	// Получить информацию об одном уроке
	// (GET /courses/{courseId}/sections/{sectionId}/lessons/{lessonId})
	LessonsGetById(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, lessonId int)
	// Обновить урок (для преподавателей/админов)
	// (PATCH /courses/{courseId}/sections/{sectionId}/lessons/{lessonId})
	LessonsUpdate(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, lessonId int)
	// Обновить прогресс урока
	// (PATCH /me/courses/{courseId}/lessons/{lessonId}/progress)
	ProgressUpdateLessonProgress(w http.ResponseWriter, r *http.Request, courseId int, lessonId int)
	// Прогресс пользователя по всем курсам
	// (GET /me/progress)
	ProgressGetUserProgress(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Авторизация пользователя
// (POST /auth/login)
func (_ Unimplemented) AuthLoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация нового пользователя
// (POST /auth/register)
func (_ Unimplemented) AuthRegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список всех опубликованных курсов (для всех пользователей)
// (GET /courses)
func (_ Unimplemented) CoursesList(w http.ResponseWriter, r *http.Request, params CoursesListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создание нового курса (только для преподавателей и админов)
// (POST /courses)
func (_ Unimplemented) CoursesCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить курс (только для админов или владельца)
// (DELETE /courses/{courseId})
func (_ Unimplemented) CoursesDelete(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить подробную информацию о курсе
// (GET /courses/{courseId})
func (_ Unimplemented) CoursesGetById(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Частично обновить курс (для преподавателей и админов)
// (PATCH /courses/{courseId})
func (_ Unimplemented) CoursesUpdate(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Записаться на курс / купить курс
// (POST /courses/{courseId}/enroll)
func (_ Unimplemented) EnrollmentsEnrollInCourse(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить все разделы курса
// (GET /courses/{courseId}/sections)
func (_ Unimplemented) CoursesGetSections(w http.ResponseWriter, r *http.Request, courseId int, params CoursesGetSectionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новый раздел в курсе (для преподавателей/админов)
// (POST /courses/{courseId}/sections)
func (_ Unimplemented) CoursesCreateSection(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить раздел (для преподавателей/админов)
// (DELETE /courses/{courseId}/sections/{sectionId})
func (_ Unimplemented) SectionsDelete(w http.ResponseWriter, r *http.Request, courseId int, sectionId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию об одном разделе курса
// (GET /courses/{courseId}/sections/{sectionId})
func (_ Unimplemented) SectionsGetById(w http.ResponseWriter, r *http.Request, courseId int, sectionId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить раздел (для преподавателей/админов)
// (PATCH /courses/{courseId}/sections/{sectionId})
func (_ Unimplemented) SectionsUpdate(w http.ResponseWriter, r *http.Request, courseId int, sectionId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список всех уроков в разделе курса
// (GET /courses/{courseId}/sections/{sectionId}/lessons)
func (_ Unimplemented) SectionsGetLessons(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, params SectionsGetLessonsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новый урок в разделе (для преподавателей/админов)
// (POST /courses/{courseId}/sections/{sectionId}/lessons)
func (_ Unimplemented) SectionsCreateLesson(w http.ResponseWriter, r *http.Request, courseId int, sectionId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить урок (для преподавателей/админов)
// (DELETE /courses/{courseId}/sections/{sectionId}/lessons/{lessonId})
func (_ Unimplemented) LessonsDelete(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, lessonId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию об одном уроке
// (GET /courses/{courseId}/sections/{sectionId}/lessons/{lessonId})
func (_ Unimplemented) LessonsGetById(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, lessonId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить урок (для преподавателей/админов)
// (PATCH /courses/{courseId}/sections/{sectionId}/lessons/{lessonId})
func (_ Unimplemented) LessonsUpdate(w http.ResponseWriter, r *http.Request, courseId int, sectionId int, lessonId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить прогресс урока
// (PATCH /me/courses/{courseId}/lessons/{lessonId}/progress)
func (_ Unimplemented) ProgressUpdateLessonProgress(w http.ResponseWriter, r *http.Request, courseId int, lessonId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Прогресс пользователя по всем курсам
// (GET /me/progress)
func (_ Unimplemented) ProgressGetUserProgress(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthLoginUser operation middleware
func (siw *ServerInterfaceWrapper) AuthLoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRegisterUser operation middleware
func (siw *ServerInterfaceWrapper) AuthRegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesList operation middleware
func (siw *ServerInterfaceWrapper) CoursesList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CoursesListParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", r.URL.Query(), &params.Category)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		return
	}

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameter("form", true, false, "level", r.URL.Query(), &params.Level)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesCreate operation middleware
func (siw *ServerInterfaceWrapper) CoursesCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesDelete operation middleware
func (siw *ServerInterfaceWrapper) CoursesDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesDelete(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesGetById operation middleware
func (siw *ServerInterfaceWrapper) CoursesGetById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesGetById(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesUpdate operation middleware
func (siw *ServerInterfaceWrapper) CoursesUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesUpdate(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollmentsEnrollInCourse operation middleware
func (siw *ServerInterfaceWrapper) EnrollmentsEnrollInCourse(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollmentsEnrollInCourse(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesGetSections operation middleware
func (siw *ServerInterfaceWrapper) CoursesGetSections(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CoursesGetSectionsParams

	// ------------- Optional query parameter "includeUnpublished" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeUnpublished", r.URL.Query(), &params.IncludeUnpublished)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "includeUnpublished", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesGetSections(w, r, courseId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CoursesCreateSection operation middleware
func (siw *ServerInterfaceWrapper) CoursesCreateSection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CoursesCreateSection(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SectionsDelete operation middleware
func (siw *ServerInterfaceWrapper) SectionsDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SectionsDelete(w, r, courseId, sectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SectionsGetById operation middleware
func (siw *ServerInterfaceWrapper) SectionsGetById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SectionsGetById(w, r, courseId, sectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SectionsUpdate operation middleware
func (siw *ServerInterfaceWrapper) SectionsUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SectionsUpdate(w, r, courseId, sectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SectionsGetLessons operation middleware
func (siw *ServerInterfaceWrapper) SectionsGetLessons(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SectionsGetLessonsParams

	// ------------- Optional query parameter "publishedOnly" -------------

	err = runtime.BindQueryParameter("form", true, false, "publishedOnly", r.URL.Query(), &params.PublishedOnly)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publishedOnly", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SectionsGetLessons(w, r, courseId, sectionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SectionsCreateLesson operation middleware
func (siw *ServerInterfaceWrapper) SectionsCreateLesson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SectionsCreateLesson(w, r, courseId, sectionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LessonsDelete operation middleware
func (siw *ServerInterfaceWrapper) LessonsDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	// ------------- Path parameter "lessonId" -------------
	var lessonId int

	err = runtime.BindStyledParameterWithOptions("simple", "lessonId", chi.URLParam(r, "lessonId"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LessonsDelete(w, r, courseId, sectionId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LessonsGetById operation middleware
func (siw *ServerInterfaceWrapper) LessonsGetById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	// ------------- Path parameter "lessonId" -------------
	var lessonId int

	err = runtime.BindStyledParameterWithOptions("simple", "lessonId", chi.URLParam(r, "lessonId"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LessonsGetById(w, r, courseId, sectionId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LessonsUpdate operation middleware
func (siw *ServerInterfaceWrapper) LessonsUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "sectionId" -------------
	var sectionId int

	err = runtime.BindStyledParameterWithOptions("simple", "sectionId", chi.URLParam(r, "sectionId"), &sectionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sectionId", Err: err})
		return
	}

	// ------------- Path parameter "lessonId" -------------
	var lessonId int

	err = runtime.BindStyledParameterWithOptions("simple", "lessonId", chi.URLParam(r, "lessonId"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LessonsUpdate(w, r, courseId, sectionId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProgressUpdateLessonProgress operation middleware
func (siw *ServerInterfaceWrapper) ProgressUpdateLessonProgress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "lessonId" -------------
	var lessonId int

	err = runtime.BindStyledParameterWithOptions("simple", "lessonId", chi.URLParam(r, "lessonId"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProgressUpdateLessonProgress(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProgressGetUserProgress operation middleware
func (siw *ServerInterfaceWrapper) ProgressGetUserProgress(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProgressGetUserProgress(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.AuthLoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.AuthRegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses", wrapper.CoursesList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses", wrapper.CoursesCreate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/courses/{courseId}", wrapper.CoursesDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}", wrapper.CoursesGetById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/courses/{courseId}", wrapper.CoursesUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseId}/enroll", wrapper.EnrollmentsEnrollInCourse)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}/sections", wrapper.CoursesGetSections)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseId}/sections", wrapper.CoursesCreateSection)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/courses/{courseId}/sections/{sectionId}", wrapper.SectionsDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}/sections/{sectionId}", wrapper.SectionsGetById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/courses/{courseId}/sections/{sectionId}", wrapper.SectionsUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}/sections/{sectionId}/lessons", wrapper.SectionsGetLessons)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseId}/sections/{sectionId}/lessons", wrapper.SectionsCreateLesson)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/courses/{courseId}/sections/{sectionId}/lessons/{lessonId}", wrapper.LessonsDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}/sections/{sectionId}/lessons/{lessonId}", wrapper.LessonsGetById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/courses/{courseId}/sections/{sectionId}/lessons/{lessonId}", wrapper.LessonsUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me/courses/{courseId}/lessons/{lessonId}/progress", wrapper.ProgressUpdateLessonProgress)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/progress", wrapper.ProgressGetUserProgress)
	})

	return r
}
