// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CourseLevel.
const (
	Advanced     CourseLevel = "advanced"
	Beginner     CourseLevel = "beginner"
	Intermediate CourseLevel = "intermediate"
)

// Defines values for CourseStatus.
const (
	Archived  CourseStatus = "archived"
	Draft     CourseStatus = "draft"
	Published CourseStatus = "published"
)

// Defines values for EnrollmentStatus.
const (
	Active    EnrollmentStatus = "active"
	Completed EnrollmentStatus = "completed"
	Expired   EnrollmentStatus = "expired"
	Refunded  EnrollmentStatus = "refunded"
)

// Defines values for UserRole.
const (
	Admin      UserRole = "admin"
	Instructor UserRole = "instructor"
	Student    UserRole = "student"
)

// Course defines model for Course.
type Course struct {
	CoverUrl    *string       `json:"coverUrl,omitempty"`
	CreatedAt   *time.Time    `json:"createdAt,omitempty"`
	Currency    *string       `json:"currency,omitempty"`
	Description *string       `json:"description,omitempty"`
	Id          *int64        `json:"id,omitempty"`
	Level       *CourseLevel  `json:"level,omitempty"`
	Price       *float32      `json:"price,omitempty"`
	Slug        *string       `json:"slug,omitempty"`
	Status      *CourseStatus `json:"status,omitempty"`
	Subtitle    *string       `json:"subtitle,omitempty"`
	Title       *string       `json:"title,omitempty"`
}

// CourseLevel defines model for Course.Level.
type CourseLevel string

// CourseStatus defines model for Course.Status.
type CourseStatus string

// Enrollment defines model for Enrollment.
type Enrollment struct {
	CompletedAt *time.Time `json:"completedAt"`
	EnrolledAt  *time.Time `json:"enrolledAt,omitempty"`
	Id          *int64     `json:"id,omitempty"`

	// Progress 0-100
	Progress *float32          `json:"progress,omitempty"`
	Status   *EnrollmentStatus `json:"status,omitempty"`
}

// EnrollmentStatus defines model for Enrollment.Status.
type EnrollmentStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

// Section defines model for Section.
type Section struct {
	// EstimatedTime minutes
	EstimatedTime *int    `json:"estimatedTime,omitempty"`
	Id            *int64  `json:"id,omitempty"`
	IsFreePreview *bool   `json:"isFreePreview,omitempty"`
	Order         *int    `json:"order,omitempty"`
	Title         *string `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string              `json:"avatarUrl"`
	CreatedAt *time.Time           `json:"createdAt,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	FullName  *string              `json:"fullName,omitempty"`
	Id        *int64               `json:"id,omitempty"`
	Role      *UserRole            `json:"role,omitempty"`
}

// UserRole defines model for User.Role.
type UserRole string

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostAuthRegisterJSONBody defines parameters for PostAuthRegister.
type PostAuthRegisterJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Password string              `json:"password"`
}

// GetCoursesParams defines parameters for GetCourses.
type GetCoursesParams struct {
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Category *string `form:"category,omitempty" json:"category,omitempty"`
	Level    *string `form:"level,omitempty" json:"level,omitempty"`
}

// PostCoursesJSONBody defines parameters for PostCourses.
type PostCoursesJSONBody struct {
	Currency    *string  `json:"currency,omitempty"`
	Description *string  `json:"description,omitempty"`
	Level       *string  `json:"level,omitempty"`
	Price       *float32 `json:"price,omitempty"`
	Slug        string   `json:"slug"`
	Subtitle    *string  `json:"subtitle,omitempty"`
	Title       string   `json:"title"`
}

// PostCoursesCourseIdEnrollJSONBody defines parameters for PostCoursesCourseIdEnroll.
type PostCoursesCourseIdEnrollJSONBody struct {
	PromoCode *string `json:"promoCode,omitempty"`
}

// PatchMeCoursesCourseIdLessonsLessonIdProgressJSONBody defines parameters for PatchMeCoursesCourseIdLessonsLessonIdProgress.
type PatchMeCoursesCourseIdLessonsLessonIdProgressJSONBody struct {
	Completed      *bool    `json:"completed,omitempty"`
	LastWatchedSec *int     `json:"lastWatchedSec,omitempty"`
	Percent        *float32 `json:"percent,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody PostAuthRegisterJSONBody

// PostCoursesJSONRequestBody defines body for PostCourses for application/json ContentType.
type PostCoursesJSONRequestBody PostCoursesJSONBody

// PostCoursesCourseIdEnrollJSONRequestBody defines body for PostCoursesCourseIdEnroll for application/json ContentType.
type PostCoursesCourseIdEnrollJSONRequestBody PostCoursesCourseIdEnrollJSONBody

// PatchMeCoursesCourseIdLessonsLessonIdProgressJSONRequestBody defines body for PatchMeCoursesCourseIdLessonsLessonIdProgress for application/json ContentType.
type PatchMeCoursesCourseIdLessonsLessonIdProgressJSONRequestBody PatchMeCoursesCourseIdLessonsLessonIdProgressJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Авторизация пользователя
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Регистрация нового пользователя
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Список всех опубликованных курсов
	// (GET /courses)
	GetCourses(w http.ResponseWriter, r *http.Request, params GetCoursesParams)
	// Создание нового курса (только для преподавателей и админов)
	// (POST /courses)
	PostCourses(w http.ResponseWriter, r *http.Request)
	// Получить подробную информацию о курсе
	// (GET /courses/{courseId})
	GetCoursesCourseId(w http.ResponseWriter, r *http.Request, courseId int)
	// Записаться на курс / купить курс
	// (POST /courses/{courseId}/enroll)
	PostCoursesCourseIdEnroll(w http.ResponseWriter, r *http.Request, courseId int)
	// Получить все разделы курса
	// (GET /courses/{courseId}/sections)
	GetCoursesCourseIdSections(w http.ResponseWriter, r *http.Request, courseId int)
	// Обновить прогресс урока
	// (PATCH /me/courses/{courseId}/lessons/{lessonId}/progress)
	PatchMeCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request, courseId int, lessonId int)
	// Прогресс пользователя по всем курсам
	// (GET /me/progress)
	GetMeProgress(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Авторизация пользователя
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация нового пользователя
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список всех опубликованных курсов
// (GET /courses)
func (_ Unimplemented) GetCourses(w http.ResponseWriter, r *http.Request, params GetCoursesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создание нового курса (только для преподавателей и админов)
// (POST /courses)
func (_ Unimplemented) PostCourses(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить подробную информацию о курсе
// (GET /courses/{courseId})
func (_ Unimplemented) GetCoursesCourseId(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Записаться на курс / купить курс
// (POST /courses/{courseId}/enroll)
func (_ Unimplemented) PostCoursesCourseIdEnroll(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить все разделы курса
// (GET /courses/{courseId}/sections)
func (_ Unimplemented) GetCoursesCourseIdSections(w http.ResponseWriter, r *http.Request, courseId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить прогресс урока
// (PATCH /me/courses/{courseId}/lessons/{lessonId}/progress)
func (_ Unimplemented) PatchMeCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request, courseId int, lessonId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Прогресс пользователя по всем курсам
// (GET /me/progress)
func (_ Unimplemented) GetMeProgress(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCourses operation middleware
func (siw *ServerInterfaceWrapper) GetCourses(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCoursesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", r.URL.Query(), &params.Category)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		return
	}

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameter("form", true, false, "level", r.URL.Query(), &params.Level)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCourses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCourses operation middleware
func (siw *ServerInterfaceWrapper) PostCourses(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCourses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCoursesCourseId operation middleware
func (siw *ServerInterfaceWrapper) GetCoursesCourseId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoursesCourseId(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCoursesCourseIdEnroll operation middleware
func (siw *ServerInterfaceWrapper) PostCoursesCourseIdEnroll(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCoursesCourseIdEnroll(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCoursesCourseIdSections operation middleware
func (siw *ServerInterfaceWrapper) GetCoursesCourseIdSections(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoursesCourseIdSections(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchMeCoursesCourseIdLessonsLessonIdProgress operation middleware
func (siw *ServerInterfaceWrapper) PatchMeCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "courseId" -------------
	var courseId int

	err = runtime.BindStyledParameterWithOptions("simple", "courseId", chi.URLParam(r, "courseId"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "courseId", Err: err})
		return
	}

	// ------------- Path parameter "lessonId" -------------
	var lessonId int

	err = runtime.BindStyledParameterWithOptions("simple", "lessonId", chi.URLParam(r, "lessonId"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lessonId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchMeCoursesCourseIdLessonsLessonIdProgress(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeProgress operation middleware
func (siw *ServerInterfaceWrapper) GetMeProgress(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeProgress(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses", wrapper.GetCourses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses", wrapper.PostCourses)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}", wrapper.GetCoursesCourseId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/courses/{courseId}/enroll", wrapper.PostCoursesCourseIdEnroll)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{courseId}/sections", wrapper.GetCoursesCourseIdSections)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me/courses/{courseId}/lessons/{lessonId}/progress", wrapper.PatchMeCoursesCourseIdLessonsLessonIdProgress)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/progress", wrapper.GetMeProgress)
	})

	return r
}
